server:
  port: 80
spring:
  cloud:
    stream:
      binders:
        rabbitbinder:
          type: rabbit
          environment:
            spring:
              rabbitmq:
                addresses: 127.0.0.1
                port: 5672
                username: guest
                password: guest
                virtual-host: /
      bindings:
        log_consumer:
          destination: notificationlog
          content-type: application/json
          default-binder: rabbitbinder
          group: log
        log_producer:
          destination: notificationlog
          content-type: application/json
          default-binder: rabbitbinder
      rabbit:
        bindings:
          log_consumer:
            consumer:
              acknowledgemode: manual
              maxAttempts: 3
              autoBindDlq: true
              republishToDlq: true
              requeueRejected: false
              dlq-ttl: 5000
              dlqDeadLetterExchange: notificationlog