server:
  port: 8762

spring:
  application:
    #工程名称
    name: service-one
  cloud:
    config:
      discovery:
        enabled: true
        service-id: config-server
      profile: dev
      label: master
      name: config-client
eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8761/eureka/